dist: trusty
sudo: false

language: python

addons:
  apt:
    update: true
    packages:
      - cmake
      - libicu-dev

.mixins:
  - &xenial-mixin
    dist: xenial
    sudo: true

jobs:
  include:
    - python: 3.6
    - <<: *xenial-mixin
      python: 3.7

env:
  - SRC_DIR=llb3d

# command to install dependencies
install:
  - python setup.py sdist bdist_egg bdist_wheel
  - pip install -e ".[dev]"

# command to run tests
jobs:
  include:
    - script: pytest --cov "${SRC_DIR}"
    - script: pylint "${SRC_DIR}"
    - stage: deploy
      script: skip
      deploy:
        provider: pypi
        user: "${PYPI_LOGIN}"
        password: "${PYPI_PASSWORD}"
        on:
          tags: true
