dist: trusty
sudo: false

language: python

addons:
  apt:
    update: true
    packages:
      - cmake
      - libicu-dev

.mixins:
  - &xenial-mixin
    dist: xenial
    sudo: true
  # command to run tests
  - &run-test-mixin
    script:
      - pytest --cov "${SRC_DIR}"
      - pylint "${SRC_DIR}"

env:
  - SRC_DIR=llb3d

# command to install dependencies
install:
  - python setup.py sdist bdist_egg bdist_wheel
  - pip install -e ".[dev]"

jobs:
  include:
    - python: 3.6
      <<: *run-test-mixin
    - <<: *xenial-mixin
      python: 3.7
      <<: *run-test-mixin
    - stage: deploy
      on:
        tags: true
      script: skip
      deploy:
        provider: pypi
        user: "${PYPI_LOGIN}"
        password: "${PYPI_PASSWORD}"
