dist: trusty
sudo: false

language: python

.mixins:
- &xenial-mixin
  dist: xenial
  sudo: true
  addons:
  apt:
    packages:
      - libgnutls-dev

jobs:
  include:
    - python: 3.5
    - python: 3.6
    - python: pypy3.5-5.10.1
    - <<: *xenial-mixin
      python: 3.7
    - <<: *xenial-mixin
      python: nightly

env:
  - SRC_DIR=llb3d

# command to install dependencies
install:
  - python setup.py sdist bdist_egg bdist_wheel
  - pip install .[dev]

# command to run tests
script:
  - pytest --cov ${SRC_DIR}
  - pep257 ${SRC_DIR}
  - pylint ${SRC_DIR}
