%token <integer> NUMBER
%token <string> ID

%token TOKEN_EOL

%token TOKEN_PLUS
%token TOKEN_MINUS
%token TOKEN_TILDA
%token TOKEN_CARET
%token TOKEN_MULTIPLY
%token TOKEN_DIVIDE

%token TOKEN_LESS
%token TOKEN_MORE
%token TOKEN_LESS_OR_EQUAL
%token TOKEN_MORE_OR_EQUAL
%token TOKEN_EQUAL
%token TOKEN_NOT_EQUAL

%token TOKEN_BRACE_OPEN
%token TOKEN_BRACE_CLOSE
%token TOKEN_SEMICOLON
