PROGRAM : PROGRAM TOKEN_EOL STATEMENT | STATEMENT ;

STATEMENT : ASSIGNATION | ;

ASSIGNATION : ID TOKEN_EQUAL EXPRESSION ;

EXPRESSION : EXPRESSION TOKEN_PLUS TERM | EXPRESSION TOKEN_MINUS TERM | TERM ;

TERM : TERM TOKEN_MULTIPLY FACTOR | TERM TOKEN_DIVIDE FACTOR | FACTOR ;

FACTOR : TOKEN_BRACE_OPEN EXPRESSION TOKEN_BRACE_CLOSE | NUMBER | ID ;

