PROGRAM:          PROGRAM TOKEN_EOL GLOBAL_STATEMENT | GLOBAL_STATEMENT;
GLOBAL_STATEMENT: GLOBAL_DEFINE | LOCAL_STATEMENT ;

STATEMENT:  LOCAL_DEFINE | ASSIGNMENT;

GLOBAL_DEFINE:      KEYWORD_GLOBAL COMMON_DEFINE;
LOCAL_DEFINE:       KEYWORD_LOCAL COMMON_DEFINE;
COMMON_DEFINE:      COMMON_DEFINE TOKEN_SEMICOLON REGISTER_VARIABLE | REGISTER_VARIABLE;
REGISTER_VARIABLE:  ID | ID TOKEN_EQUAL RVALUE;



ASSIGNMENT: LVALUE TOKEN_EQUAL RVALUE;

LVALUE: ID;
RVALUE: EXPRESSION;
